### ISSUE TITLE
Issue with Jena Dependency

### ISSUE THREAD

**Issue by ram-g-athreya** [AKSW/SemWeb2NL#22]
Hi

I am trying to use Avatar for entity summarization for my GSoC Project. I tried executing the following snippet of code similar to the Verbalizer Test Case:

    OWLIndividual ind = new OWLNamedIndividualImpl(IRI.create("http://dbpedia.org/resource/Albert_Einstein"));
    SparqlEndpoint endpoint = SparqlEndpoint.getEndpointDBpedia();
    Verbalizer verbalizer = new Verbalizer(endpoint, "cache", null);

    //compute summarization of the entity and verbalize it
    String summary = verbalizer.summarize(ind);
    System.out.println(summary);

I am getting a NoClassDefFoundError for class **ParameterizedSparqlString**. Detailed stacktrace below.

I am using **com.hp.hpl.jena.arq 2.8.8** which is the maximum version available in [mvn repository](https://mvnrepository.com/artifact/com.hp.hpl.jena/arq/2.8.8). This particular class is available in later versions such as 2.9.4 but those are not available in MVN Repository. Would it be possible to add the dependency to AKSW Archiva so that I can use it from there or any other solution via maven is also welcome.

On a related not **com.hp.hpl.jena.arq** has been inactive for many years, instead would it be possible to use **org.apache.jena 3.3.0** which is more recent and also has the class in question and the same APIs.

`Exception in thread "main" java.lang.NoClassDefFoundError: com/hp/hpl/jena/query/ParameterizedSparqlString
	at org.dllearner.reasoning.SPARQLReasoner.<clinit>(SPARQLReasoner.java:98)
	at org.aksw.triple2nl.functionality.SPARQLFunctionalityDetector.<init>(SPARQLFunctionalityDetector.java:21)
	at org.aksw.sparql2nl.naturallanguagegeneration.SimpleNLGwithPostprocessing.init(SimpleNLGwithPostprocessing.java:181)
	at org.aksw.sparql2nl.naturallanguagegeneration.SimpleNLGwithPostprocessing.<init>(SimpleNLGwithPostprocessing.java:144)
	at org.aksw.avatar.Verbalizer.<init>(Verbalizer.java:112)
	at org.aksw.avatar.Verbalizer.<init>(Verbalizer.java:127)
	at chatbot.Test.main(Test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: com.hp.hpl.jena.query.ParameterizedSparqlString
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more`

**Comment by LorenzBuehmann** [comment]
Short answer: Don't use the `master` branch. This wasn't updated for a long time and there wasn't done any release as far as I can remember. The `develop` branch instead is based on Jena 3.x .

**Comment by ram-g-athreya** [comment]
Thanks I was able to get it to work as you suggested
