### ISSUE TITLE
Locale.UK erzeugt auf Windows und java 1.8.0_40-b26 andere Zeichenketten, als in TripleConverterTest vorgesehen

### ISSUE THREAD

**Issue by dhaeb** [AKSW/SemWeb2NL#4]
In #3 ist die Anpassung auf die Locale.UK erfolgt. Dennoch laufen die Tests nicht fehlerfrei durch, da die Ausgabe der Dateumkonvertierung unterschiedlich zur Vorgabe ist.
Ich habe das mal in LiteralConverterTest simuliert:

Expected: June 27, 1869
Result:      27 June 1869

Es hat sich ja mit Java 8 einiges an der Zeitbibliothek getan - also ist mein Tipp wo man suchen kann. Bitte schaut mal rein, dass das zukünftig stabil ist.

**Comment by LorenzBuehmann** [comment]
Also, so genau kann ich das nicht reproduzieren. Es lag wohl daran dass kein Locale angegeben wurde. Mit Locale.UK ist das format allerdings klar spezifiziert auf

27 June 1869

und mit Locale.US

June 27, 1869

siehe https://docs.oracle.com/javase/tutorial/i18n/format/dateFormat.html .

Ich habe die Unit-Tests jetzt auf UK Format umgestellt. Bei mir läuft es durch.

**Comment by dhaeb** [comment]
Hey, 
ja sieht gut aus und geht bei mir, was das Zeitformat angeht. Ich hab nur noch folgenden Testfehler, welcher aber ein Reihenfolgenproblem der NL zu sein scheint: 

```
-------------------------------------------------------------------------------
Test set: org.aksw.triple2nl.TripleConverterTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 17.892 sec <<< FAILURE!
testConvertTriplesToText(org.aksw.triple2nl.TripleConverterTest)  Time elapsed: 1.216 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...
rson, whose's birth [place is Ulm and whose's birth date is 14 March 1879].> but was:<...
rson, whose's birth [date is 14 March 1879 and whose's birth place is Ulm].>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.aksw.triple2nl.TripleConverterTest.testConvertTriplesToText(TripleConverterTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
```

**Comment by LorenzBuehmann** [comment]
Ok, verstehe das Problem. Sollte jetzt aber funktionieren.
